version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 8761:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8762:8080

  www:
    depends_on:
      - db
    build: .
    volumes:
      - ./public_html/:/var/www/html/
    ports:
      - 8763:80

